/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrefsRouteImport } from './routes/prefs'
import { Route as NoMatchRouteImport } from './routes/no-match'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoRouteImport } from './routes/go'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ConflictRouteImport } from './routes/conflict'
import { Route as CompromiseRouteImport } from './routes/compromise'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefsRoute = PrefsRouteImport.update({
  id: '/prefs',
  path: '/prefs',
  getParentRoute: () => rootRouteImport,
} as any)
const NoMatchRoute = NoMatchRouteImport.update({
  id: '/no-match',
  path: '/no-match',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictRoute = ConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const CompromiseRoute = CompromiseRouteImport.update({
  id: '/compromise',
  path: '/compromise',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compromise': typeof CompromiseRoute
  '/conflict': typeof ConflictRoute
  '/create': typeof CreateRoute
  '/feedback': typeof FeedbackRoute
  '/go': typeof GoRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/no-match': typeof NoMatchRoute
  '/prefs': typeof PrefsRoute
  '/results': typeof ResultsRoute
  '/summary': typeof SummaryRoute
  '/welcome': typeof WelcomeRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compromise': typeof CompromiseRoute
  '/conflict': typeof ConflictRoute
  '/create': typeof CreateRoute
  '/feedback': typeof FeedbackRoute
  '/go': typeof GoRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/no-match': typeof NoMatchRoute
  '/prefs': typeof PrefsRoute
  '/results': typeof ResultsRoute
  '/summary': typeof SummaryRoute
  '/welcome': typeof WelcomeRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compromise': typeof CompromiseRoute
  '/conflict': typeof ConflictRoute
  '/create': typeof CreateRoute
  '/feedback': typeof FeedbackRoute
  '/go': typeof GoRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/no-match': typeof NoMatchRoute
  '/prefs': typeof PrefsRoute
  '/results': typeof ResultsRoute
  '/summary': typeof SummaryRoute
  '/welcome': typeof WelcomeRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/compromise'
    | '/conflict'
    | '/create'
    | '/feedback'
    | '/go'
    | '/history'
    | '/invite'
    | '/join'
    | '/lobby'
    | '/no-match'
    | '/prefs'
    | '/results'
    | '/summary'
    | '/welcome'
    | '/activity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/compromise'
    | '/conflict'
    | '/create'
    | '/feedback'
    | '/go'
    | '/history'
    | '/invite'
    | '/join'
    | '/lobby'
    | '/no-match'
    | '/prefs'
    | '/results'
    | '/summary'
    | '/welcome'
    | '/activity/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/compromise'
    | '/conflict'
    | '/create'
    | '/feedback'
    | '/go'
    | '/history'
    | '/invite'
    | '/join'
    | '/lobby'
    | '/no-match'
    | '/prefs'
    | '/results'
    | '/summary'
    | '/welcome'
    | '/activity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompromiseRoute: typeof CompromiseRoute
  ConflictRoute: typeof ConflictRoute
  CreateRoute: typeof CreateRoute
  FeedbackRoute: typeof FeedbackRoute
  GoRoute: typeof GoRoute
  HistoryRoute: typeof HistoryRoute
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRoute
  LobbyRoute: typeof LobbyRoute
  NoMatchRoute: typeof NoMatchRoute
  PrefsRoute: typeof PrefsRoute
  ResultsRoute: typeof ResultsRoute
  SummaryRoute: typeof SummaryRoute
  WelcomeRoute: typeof WelcomeRoute
  ActivityIdRoute: typeof ActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefs': {
      id: '/prefs'
      path: '/prefs'
      fullPath: '/prefs'
      preLoaderRoute: typeof PrefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-match': {
      id: '/no-match'
      path: '/no-match'
      fullPath: '/no-match'
      preLoaderRoute: typeof NoMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict': {
      id: '/conflict'
      path: '/conflict'
      fullPath: '/conflict'
      preLoaderRoute: typeof ConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compromise': {
      id: '/compromise'
      path: '/compromise'
      fullPath: '/compromise'
      preLoaderRoute: typeof CompromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompromiseRoute: CompromiseRoute,
  ConflictRoute: ConflictRoute,
  CreateRoute: CreateRoute,
  FeedbackRoute: FeedbackRoute,
  GoRoute: GoRoute,
  HistoryRoute: HistoryRoute,
  InviteRoute: InviteRoute,
  JoinRoute: JoinRoute,
  LobbyRoute: LobbyRoute,
  NoMatchRoute: NoMatchRoute,
  PrefsRoute: PrefsRoute,
  ResultsRoute: ResultsRoute,
  SummaryRoute: SummaryRoute,
  WelcomeRoute: WelcomeRoute,
  ActivityIdRoute: ActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
